### PR TITLE
Do not call js callback before js engine prepared.

### PR DESCRIPTION
**Pull request by armbox**
Ok, this time, it's correct fix.

Thanks,

### CODE REVIEW

**Comment by d4vidi** [comment]
LGTM!
But please run some styling fixes -
1. space after 'if'
2. Add enclosing brackets to if clause -- i.e. {}

🙏

**Comment by armbox** [comment]
@d4vidi NP, My pleasure. 
Did it.

Thanks,

**Comment by d4vidi** [comment]
@artald can publish?

**Comment by artald** [comment]
@d4vidi  published - `v5.2.1`

**Pull request merged**
